#!/usr/bin/env bash

ROOT_DIR="$(dirname "$0")"

option=$1

export ROOT_DIR
export option

"$ROOT_DIR/install_scripts/mac_install.sh"
"$ROOT_DIR/install_scripts/ubuntu_install.sh"
"$ROOT_DIR/install_scripts/python.sh"
"$ROOT_DIR/install_scripts/zsh.sh"
"$ROOT_DIR/install_scripts/terminal_tools.sh"
