customCommands:
  - key: "I"
    description: "Ignore file locally (.git/info/exclude)"
    context: "files"
    command: >
      sh -c 'echo "{{.SelectedFile.Name}}" >> .git/info/exclude'

git:
  autoFetch: true

gui:
  showDivergenceFromBaseBranch: 'arrowAndNumber'

  skipSwitchWorktreeOnCheckoutWarning: true

  mainBranches:
    - lua
    - master
    - main

os:
  editPreset: 'nvim'
