"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[](silver)\
$os\
[](silver)\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$line_break\
$character"""


palette = 'catppuccin_mocha'

[os]
disabled = false
style = "bg:silver fg:crust"
format = '[ $symbol ]($style)'

[os.symbols]
Windows = ""
Ubuntu = " "
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[hostname]
ssh_only = true
format = '[](pink)[$hostname](bg:pink fg:bold crust)[](pink)'
disabled = false

[username]
show_always = true
style_user = "bg:pink fg:crust"
style_root = "bg:pink fg:crust"
format = '[$user@]($style)'

[directory]

style = "bg:sky fg:crust"
format = "[](sky)[  ](bg:sky fg:crust)(sky)[$path ]($style)[](sky)"
truncation_length = 1

[git_branch]
symbol = ""
style = "bg:green"
format = '[[](green)[ $symbol $branch ](fg:crust bg:green)[](green)]($style)'

[git_status]
style = "bg:yellow"
format = '[[](yellow)[(($conflicted )($deleted )($modified )($staged )($untracked )$ahead_behind)](fg:bold crust bg:yellow)[](yellow)]($style)'
up_to_date='✓'
conflicted = '='
untracked = '?$count'
modified = '!$count'
staged = '[+ $count](fg:bold crust bg:yellow)'
deleted = '✘ $count'
ahead="⇡$count"
behind="⇣$count"

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[python]
symbol = ""
style = "bg:lavender"
format = '[[](lavender)[$symbol $virtualenv](fg:crust bg:lavender)[](lavender)]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[conda]
symbol = "◈ "
style = "fg:crust bg:lavender"
format = '[$symbol$environment ]($style)'
ignore_base = false
disabled=true

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[Σ❯❯](bold fg:green)'
error_symbol = '[Σ❯❯](bold fg:red)'
vimcmd_symbol = '[∫❯❯](bold fg:green)'
vimcmd_replace_one_symbol = '[∫❯❯](bold fg:lavender)'
vimcmd_replace_symbol = '[∫❯❯](bold fg:lavender)'
vimcmd_visual_symbol = '[∫❯❯](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = "[](teal)[ in $duration]($style)[](teal)"
style = "fg:crust bg:teal"
disabled = false
show_notifications = false
min_time_to_notify = 20000

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#B481BB"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#E8B647"
green = "#5DAC81"
teal = "#EB7A77"
sky = "#58B2DC"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
silver = "#91989F"
