#!/usr/bin/env python

import shutil
import subprocess
import sys
from typing import Any
from typing import Callable
from typing import Literal


Group = Literal["general", "multiplexer", "git", "functions"]

_REGISTERD_COMMANDS: dict[str, Any] = {}
_REGISTERED_GROUP: set[Group] = set()


def pprint_table(column_names: list[str], rows: list[tuple[Any, ...]]) -> None:
    col_widths = [
        max(len(str(item)) for item in col) for col in zip(*rows, column_names)
    ]
    format_string = " │ ".join(f"{{:<{width}}}" for width in col_widths)
    title_line = format_string.format(*column_names)
    # Print header
    header_line = "┌" + "─" * len(title_line) + "┐"
    middle_line = "├" + "─" * len(title_line) + "┤"
    footer_line = "└" + "─" * len(title_line) + "┘"
    print(header_line)
    # Removing the trailing empty spaces to make tests comparison easier.
    print("│" + title_line + "│")
    print(middle_line)
    for row in rows:
        print("│" + format_string.format(*row) + "│")
    print(footer_line)


def register_command(
    command: str, command_group: Group, description: str
) -> Callable[[Callable], Callable]:
    def decorator(func: Callable) -> Callable:
        _REGISTERD_COMMANDS[command] = {
            "description": description,
            "group": command_group,
            "command": func,
        }
        _REGISTERED_GROUP.add(command_group)
        return func

    return decorator


# General functions
@register_command("info", "general", "Get OS info")
def system_info(args: None) -> str:
    return "sw_vers"


@register_command("lock", "general", "Lock screen")
def lock_screen(args: None) -> str:
    return """osascript -e 'tell application "System Events" to keystroke "q" using {control down, command down}'"""


@register_command("ports", "general", "Get list of used ports")
def ports(args: None) -> str:
    return "sudo lsof -iTCP -sTCP:LISTEN -P"


@register_command("uptime", "general", "Get uptime")
def get_uptime(args: None) -> str:
    return "uptime"


@register_command("weather", "general", "Get weather")
def get_weather_info(args: list[str] | None) -> str:
    return "curl wttr.in"


@register_command("waka", "general", "Open wakatime dashboard")
def open_waka(args: list[str] | None) -> str:
    return "open https://wakatime.com/dashboard"


@register_command("fd.size", "general", "Get folder size")
def folder_size(args: list[str]) -> str:
    return f"du -sch {' '.join(args)}"


@register_command("disk", "general", "Print disk usage")
def disk_usage(args: None) -> str:
    if shutil.which("duf"):
        return "CLICOLOR_FORCE=1 duf -width 180"
    return "df -h"


@register_command("jpy2html", "functions", "Render jupyter notebook as html")
def render_jupyter_notebook(args: list[str]) -> str:
    file = args[0]
    outfile = file.replace(".ipynb", ".html")
    print(f"The rendered file is saved as {outfile}.")
    return f"jupyter nbconvert --to html {file}"


# Git related
@register_command("g.stat", "git", "Get git status")
def git_status(args: None) -> str:
    return "git status"


@register_command("g.clone", "git", "Clone git repository")
def git_clone(args: list[str]) -> str:
    return f"git clone {' '.join(args)}"


@register_command("g.pull", "git", "Pull git repository")
def git_pull(args: None) -> str:
    return "git pull"


@register_command("g.th.bh", "git", "Create git branch")
def git_create_branch(args: list[str]) -> str:
    return f"git checkout -b {args[0]}"


@register_command("g.co.bh", "git", "Checkout git branch")
def git_checkout_branch(args: list[str]) -> str:
    return f"git checkout {args[0]}"


@register_command("g.add", "git", "Add files")
def git_add(args: list[str]) -> str:
    return f"git add {' '.join(args)}"


@register_command("g.add.all", "git", "Add all files")
def git_add_all(args: None) -> str:
    return "git add -A"


@register_command("g.commit", "git", "Commit changes")
def git_commit(args: list[str]) -> str:
    return f'git commit -m "{args[0]}" -q'


@register_command("g.conf", "git", "Commit changes")
def git_config(args: None) -> str:
    return "git config --list"


@register_command("go", "git", "Open git repository in browser")
def open_git_repo(args: None) -> str:
    return "open `git remote -v | awk '/fetch/{print $2}' | sed -Ee 's#(git@|git://)#http://#' -e 's@com:@com/@'`| head -n1"


# TMUX related
@register_command("t.div.h", "multiplexer", "Split tmux pane horizontally")
def tmux_split_horizontal(args: None) -> str:
    return "tmux split-window -h"


@register_command("t.div.v", "multiplexer", "Split tmux pane vertically")
def tmux_split_vertical(args: None) -> str:
    return "tmux split-window -v"


@register_command("t.de", "multiplexer", "Detach tmux session")
def tmux_detach_session(args: None) -> str:
    return "tmux detach-client"


@register_command("t.at", "multiplexer", "Create new tmux session")
def attach_session(args: list[str]) -> str:
    return f"tmux new -s {args[0]} \; split-window -v -l 20% \; select-pane -t 0"


@register_command("t", "multiplexer", "Create new main tmux setup")
def attach_main_session(args: list[str]) -> str:
    session_name = "main" if len(args) == 0 else args[0]
    return (
        f"tmux new -s {session_name} -n 🧠 \; split-window -v -l 20% \; select-pane -t 0 \; "
        "new-window -n 🧾 \; split-window -v -l 20% \; select-pane -t 0 \; "
        "new-window -n 🌐 \; split-window -v -l 20% \; select-pane -t 0 \; "
        "new-window -n 🎮 \; split-window -v -l 20% \; select-pane -t 0 \; "
        "select-window -t 🧠 \; "
    )


@register_command("t.re", "multiplexer", "Re-attach new tmux session")
def reattach_session(args: list[str]) -> str:
    return f"tmux attach -t {args[0]}"


@register_command("t.ls", "multiplexer", "list tmux sessions")
def list_session(args: None) -> str:
    return "tmux list-sessions"


@register_command("t.rm", "multiplexer", "Remove tmux session")
def remove_session(args: list[str]) -> str:
    return f"tmux kill-session -t {args[0]}"


@register_command("tpx", "multiplexer", "Remove tmux pane")
def remove_pane(args: list[str]) -> str:
    return "tmux kill-pane"


@register_command("t.new", "multiplexer", "Create new tmux window")
def cerate_new_window(args: list[str]) -> str:
    if len(args) == 0:
        new_window_str = "tmux new-window"
    else:
        new_window_str = f"tmux new-window -n {args[0]}"

    return f"{new_window_str} \; split-window -v -l 20% \; select-pane -t 0"


@register_command("twx", "multiplexer", "Remove a tmux window")
def remove_window(args: list[str]) -> str:
    if len(args) == 0:
        return "tmux kill-window"
    return f"tmux kill-window -t {args[0]}"


@register_command("t.rename", "multiplexer", "Rename a tmux window")
def rename_window(args: list[str]) -> str:
    return f"tmux rename-window {args[0]}"


def run_command(command: str, args: list[str] | None) -> None:
    final_command = _REGISTERD_COMMANDS[command]["command"](args)

    results = subprocess.run(final_command, capture_output=True, shell=True)

    stdout = results.stdout.decode("utf-8")
    if stdout:
        print(stdout)


def get_commands(group: Group | None = None) -> dict[str, str]:
    if group:
        return {
            command: data["description"]
            for command, data in _REGISTERD_COMMANDS.items()
            if data["group"] == group
        }
    return {
        command: data["description"] for command, data in _REGISTERD_COMMANDS.items()
    }


def print_help(command: str | Group | None = None) -> None:
    if (
        command not in _REGISTERED_GROUP
        and command not in _REGISTERD_COMMANDS
        and command is not None
    ):
        print(f"'{command}' cannot not found as a command group or individual command.")

    if command is None:
        groups = _REGISTERED_GROUP
    elif command in _REGISTERED_GROUP:
        groups = [command]  # type: ignore
    else:
        groups = None

    if groups:
        print("Available commands:")
        for group in sorted(groups):
            pprint_table(
                [f"{group.capitalize()}", "Description"],
                [
                    (cmd, description)
                    for cmd, description in get_commands(group).items()
                ],
            )
    elif command:
        print(f"{command}: {_REGISTERD_COMMANDS[command]['description']}")


def process_args() -> tuple[str, list[str]]:
    if len(sys.argv) == 1:
        # No argument supplied, print help
        return "help", []
    elif len(sys.argv) == 2:
        return sys.argv[1], []
    else:
        return sys.argv[1], sys.argv[2:]


def main():
    command, command_args = process_args()

    if command == "help":
        if len(command_args) == 0:
            print_help()
        else:
            print_help(command_args[0])
    elif command in _REGISTERED_GROUP:
        print_help(command)
    elif command in _REGISTERD_COMMANDS:
        run_command(command, command_args)
    else:
        print(f"Command {command} not found")


if __name__ == "__main__":
    main()
