return {
    {
        "SmiteshP/nvim-navbuddy",
        event = "VeryLazy",
        dependencies = {
            "neovim/nvim-lspconfig",
            "SmiteshP/nvim-navic",
            "MunifTanjim/nui.nvim",
        },
        --stylua: ignore
        keys = {
            { "<leader>vO", function() require("nvim-navbuddy").open() end, desc = "Code Outline (navbuddy)", },
        },
        opts = {
            lsp = { auto_attach = true },
            icons = {
                File          = " ",
                Module        = " ",
                Namespace     = " ",
                Package       = " ",
                Class         = " ",
                Method        = " ",
                Property      = " ",
                Field         = " ",
                Constructor   = " ",
                Enum          = " ",
                Interface     = " ",
                Function      = "𝑓 ",
                Variable      = " ",
                Constant      = " ",
                String        = " ",
                Number        = " ",
                Boolean       = "◩ ",
                Array         = " ",
                Object        = " ",
                Key           = " ",
                Null          = "ﳠ ",
                EnumMember    = " ",
                Struct        = " ",
                Event         = " ",
                Operator      = " ",
                TypeParameter = " ",
            },
        },
    },
}
