name: Test CLI Installation

on: [push]

jobs:
  macos-install:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Homebrew
      run: |
        echo $0
        NONINTERACTIVE=1 ./install homebrew
    - name: Install CLI tools
      run: |
        ./install mac_essentials
    - name: Run list
      run: |
        brew list
    - name: Install Conda
      run: |
        ./install conda
    - name: Install omz
      run: |
        ./install omz
    - name: Install Python
      run: |
        source $HOME/.zshrc
        which python
        ./install python_commons
        ./install pytorch
        ./install python_dev

  ubuntu-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install CLI tools
      run: |
        ./install ubuntu_essentials
    - name: Install Conda
      run: |
        ./install conda
    - name: Install omz
      run: |
        ./install omz
    - name: Install Python
      run: |
        source $HOME/.bashrc
        which python
        ./install python_commons
        ./install pytorch
        ./install python_dev
