name: Test CLI Installation

on: [push]

jobs:
  macos-install:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create symblink
      run: |
        ln -s ${{ github.workspace }} $HOME/.vim
    - name: Install CLI tools
      run: |
        ./install mac_essentials
    - name: Run list
      run: |
        brew list
    - name: Install Conda
      run: |
        ./install conda
    - name: Install omz
      run: |
        brew install zsh
        exec zsh
        ./install omz
        source $HOME/.zshrc

  ubuntu-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create symblink
      run: |
        ln -s ${{ github.workspace }} $HOME/.vim
    - name: Install CLI tools
      run: |
        ./install ubuntu_essentials
    - name: Install Conda
      run: |
        rm -rf /usr/share/miniconda
        ./install conda
    - name: Install omz
      run: |
        ./install omz
