name: Test CLI Installation

on: [push]

jobs:
  macos-install:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Homebrew
      run: |
        NONINTERACTIVE=1 ./install homebrew
    - name: Install CLI tools
      run: |
        ./install mac_essentials
    - name: Run list
      run: |
        brew list
    - name: Install Conda
      run: |
        ./install conda
    - name: Switch to zsh
      run: |
        ./install switch_to_zsh
        ./install omz
