name: Test CLI Installation

on: [push]

jobs:
  macos-install:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Homebrew
      run: |
        ./install install_homebrew
    - name: Install CLI tools
      run: |
        ./install mac_install
